kind: Service
apiVersion: v1
metadata:
  name: dbservice
spec:
  type: ClusterIP
  selector:
    app: db
  ports:  
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: 10.51.240.6

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dbdeployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        env:
          - name: POSTGRES_USER
            value: webapp
          - name: POSTGRES_PASSWORD
            value: webapp
        ports:
          - containerPort: 5432



