apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdeployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: db
        image: postgres
        env:
          - name: POSTGRES_USER
            value: webapp
          - name: POSTGRES_PASSWORD
            value: webapp
        ports:
          - containerPort: 5432


      - name: videoserver
        image: sergiolopezdf/videoserver_tfg_upm
        env:
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@localhost:5432/webapp
          - name: WEBAPP_SERVER_URL
            value: localhost
          - name: WEBAPP_SERVER_PORT
            value: "3000"
        ports:
        - containerPort: 8000

      - name: forumserver
        image: sergiolopezdf/forumserver_tfg_upm
        env:
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@localhost:5432/webapp
          - name: WEBAPP_SERVER_URL
            value: localhost
          - name: WEBAPP_SERVER_PORT
            value: "3000"
            
        ports:
        - containerPort: 5000

      - name: chatserver
        image: sergiolopezdf/chatserver_tfg_upm
        env:
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@localhost:5432/webapp
          - name: WEBAPP_SERVER_URL
            value: localhost
          - name: WEBAPP_SERVER_PORT
            value: "3000"
            
        ports:
        - containerPort: 4000


      - name: webapp
        image: sergiolopezdf/webapp_tfg_upm
        env:
          - name: PORT
            value: "3000"
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@localhost:5432/webapp
          - name: VIDEO_SERVER_URL
            value: localhost
          - name: CHAT_SERVER_URL
            value: localhost
          - name: FORUM_SERVER_URL
            value: localhost
        ports:
        - containerPort: 3000

        

      