version: '2'
services:


  #Database
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=webapp #Automaticamente crea una DB con ese mismo nombre y de la que crm es superuser.
      - POSTGRES_PASSWORD=webapp
    expose:
      - "5432"
    networks:
      LAN1: 
        ipv4_address: 10.1.1.1

  #Servers
  webapp:
    build: webApp/
    image: webapp
    privileged: true
    expose:
      - "3000"
    environment: 
      - PORT=3000
      - DB_URL=postgres://webapp:webapp@10.1.1.1:5432/webapp
      - VIDEO_SERVER_URL=10.1.1.3
      - FORUM_SERVER_URL=10.1.1.5
      - CHAT_SERVER_URL=10.1.1.4
      - VIDEO_SERVER_PORT=8000
      - FORUM_SERVER_PORT=5000
      - CHAT_SERVER_PORT=4000

    networks:
      LAN1: 
        ipv4_address: 10.1.1.2

  #Servers
  video:
    build: videoServer/
    image: videoServer
    privileged: true
    expose:
      - "8000"
    environment: 
      - PORT=8000
      - DB_URL=postgres://webapp:webapp@10.1.1.1:5432/webapp
      - VIDEO_SERVER_URL=10.1.1.3
      - FORUM_SERVER_URL=10.1.1.5
      - CHAT_SERVER_URL=10.1.1.4
      - VIDEO_SERVER_PORT=8000
      - FORUM_SERVER_PORT=5000
      - CHAT_SERVER_PORT=4000

    networks:
      LAN1: 
        ipv4_address: 10.1.1.3

  #Servers
  chat:
    build: chatServer/
    image: chatServer
    privileged: true
    expose:
      - "4000"
    environment: 
      - PORT=4000
      - DB_URL=postgres://webapp:webapp@10.1.1.1:5432/webapp
      - VIDEO_SERVER_URL=10.1.1.3
      - FORUM_SERVER_URL=10.1.1.5
      - CHAT_SERVER_URL=10.1.1.4
      - VIDEO_SERVER_PORT=8000
      - FORUM_SERVER_PORT=5000
      - CHAT_SERVER_PORT=4000

    networks:
      LAN1: 
        ipv4_address: 10.1.1.4


  #Servers
  forum:
    build: forumServer/
    image: forumServer
    privileged: true
    expose:
      - "5000"
    environment: 
      - PORT=5000
      - DB_URL=postgres://webapp:webapp@10.1.1.1:5432/webapp
      - VIDEO_SERVER_URL=10.1.1.3
      - FORUM_SERVER_URL=10.1.1.5
      - CHAT_SERVER_URL=10.1.1.4
      - VIDEO_SERVER_PORT=8000
      - FORUM_SERVER_PORT=5000
      - CHAT_SERVER_PORT=4000

    networks:
      LAN1: 
        ipv4_address: 10.1.1.5


networks:
  LAN1:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 10.1.1.0/24