version: '2'
services:


  #Database
  db: 
    image: postgres
    environment:
      - POSTGRES_USER=webapp #Automaticamente crea una DB con ese mismo nombre y de la que crm es superuser.
      - POSTGRES_PASSWORD=webapp
    expose:
      - "5432"
    networks:
      LAN1: 
        ipv4_address: 10.1.1.2

  #Servers
  webapp:
    build: webApp/
    image: webapp
    privileged: true
    expose:
      - "3000"
    environment: 
      - PORT=3000
      - PRODUCTION=true
      - DATABASE_URL=postgres://webapp:webapp@10.1.1.2:5432/webapp
      - VIDEO_SERVER_URL=10.1.1.4
      - FORUM_SERVER_URL=10.1.1.6
      - CHAT_SERVER_URL=10.1.1.5
      - VIDEO_SERVER_PORT=8000
      - FORUM_SERVER_PORT=5000
      - CHAT_SERVER_PORT=4000
    command: npm start

    networks:
      LAN1: 
        ipv4_address: 10.1.1.3

  # #Servers
  # video:
  #   build: videoServer/
  #   image: videoserver
  #   privileged: true
  #   expose:
  #     - "8000"
  #   environment: 
  #     - PORT=8000
  #     - DATABASE_URL=postgres://webapp:webapp@10.1.1.2:5432/webapp
  #     - FORUM_SERVER_URL=10.1.1.6
  #     - CHAT_SERVER_URL=10.1.1.5
  #     - VIDEO_SERVER_PORT=8000
  #     - FORUM_SERVER_PORT=5000
  #     - CHAT_SERVER_PORT=4000
  #   command: npm start

  #   networks:
  #     LAN1: 
  #       ipv4_address: 10.1.1.4

  # #Servers
  # chat:
  #   build: chatServer/
  #   image: chatserver
  #   privileged: true
  #   expose:
  #     - "4000"
  #   environment: 
  #     - PORT=4000
  #     - DATABASE_URL=postgres://webapp:webapp@10.1.1.2:5432/webapp
  #     - VIDEO_SERVER_URL=10.1.1.4
  #     - FORUM_SERVER_URL=10.1.1.6
  #     - VIDEO_SERVER_PORT=8000
  #     - FORUM_SERVER_PORT=5000
  #     - CHAT_SERVER_PORT=4000
  #   command: npm start

  #   networks:
  #     LAN1: 
  #       ipv4_address: 10.1.1.5


  # #Servers
  forum:
    build: forumServer/
    image: forumserver
    privileged: true
    expose:
      - "5000"
    environment: 
      - PORT=5000
      - DATABASE_URL=postgres://webapp:webapp@10.1.1.2:5432/webapp
      - VIDEO_SERVER_URL=10.1.1.4
      - CHAT_SERVER_URL=10.1.1.5
      - VIDEO_SERVER_PORT=8000
      - FORUM_SERVER_PORT=5000
      - CHAT_SERVER_PORT=4000
    command: npm start

    networks:
      LAN1: 
        ipv4_address: 10.1.1.6


networks:
  LAN1:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 10.1.1.0/24