kind: Service
apiVersion: v1
metadata:
  name: forumserverservice
spec:
  type: LoadBalancer
  selector:
    app: forumserver
  ports:  
  - protocol: TCP
    port: 5000
  clusterIP: 10.51.240.4
      
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: forumserverdeployment
  labels:
    app: forumserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forumserver
  template:
    metadata:
      labels:
        app: forumserver
    spec:
      containers:
      - name: forumserver
        image: sergiolopezdf/forumserver_tfg_upm
        env:
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@10.51.240.6:5432/webapp
          - name: WEBAPP_SERVER_URL
            value: 10.51.240.2
          - name: WEBAPP_SERVER_PORT
            value: "3000"
          - name: FORUM_SERVER_PORT
            value: "5000"
        ports:
        - containerPort: 5000


