kind: Service
apiVersion: v1
metadata:
  name: webappservice
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:  
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  clusterIP: 10.51.240.2

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webappdeployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: sergiolopezdf/webapp_tfg_upm
        env:
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@10.51.240.6:5432/webapp
          - name: VIDEO_SERVER_URL
            value: 35.190.217.245 
          - name: VIDEO_SERVER_PORT
            value: "8000"
          - name: CHAT_SERVER_URL
            value: 104.155.14.234 
          - name: CHAT_SERVER_PORT
            value: "4000"
          - name: FORUM_SERVER_URL
            value: 35.195.70.48 
          - name: FORUM_SERVER_PORT
            value: "5000"
        ports:
        - containerPort: 3000


