kind: Service
apiVersion: v1
metadata:
  name: webappservice
spec:
  type: NodePort
  selector:
    app: webapp
  ports:  
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30001
    targetPort: 3000
  clusterIP: 10.0.1.2
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdeployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: sergiolopezdf/webapp_tfg_upm
        env:
          - name: PRODUCTION
            value: "true"
          - name: DATABASE_URL
            value: postgres://webapp:webapp@10.96.2.6:5432/webapp
          - name: VIDEO_SERVER_URL
            value: 35.192.181.223
          - name: VIDEO_SERVER_PORT
            value: "30003"
          - name: CHAT_SERVER_URL
            value: 35.192.181.223
          - name: CHAT_SERVER_PORT
            value: "30005"
          - name: FORUM_SERVER_URL
            value: 35.192.181.223
          - name: FORUM_SERVER_PORT
            value: "30004"
        ports:
        - containerPort: 3000


